#!/bin/sh

set -ev

# This shell script installs all local software required to run the
# pdf2htmlEX tests

export DEBIAN_FRONTEND=noninteractive

# Install required apt packages (Firefox is handled separately below)
#
sudo apt -y install \
  wget                       \
  diffutils                  \
  zip                        \
  python3                    \
  python3-pip                \
  xvfb                       \
  software-properties-common

# Install Firefox as a proper deb package via Mozilla PPA.
# On Ubuntu 22.04+, "apt install firefox" installs a snap wrapper that
# does not work in headless/Xvfb environments.
#
sudo add-apt-repository -y ppa:mozillateam/ppa
printf 'Package: *\nPin: release o=LP-PPA-mozillateam\nPin-Priority: 1001\n' \
  | sudo tee /etc/apt/preferences.d/mozilla-firefox
sudo apt -y update
sudo apt -y install firefox

# Install geckodriver (the WebDriver bridge for Firefox / Selenium)
#
GECKODRIVER_VERSION=0.35.0
oldPWD=$(pwd)
cd /tmp
#
wget https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
#
tar xvf geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
#
sudo mv geckodriver /usr/local/bin
#
cd $oldPWD

# Install Python test packages
#
pip3 install \
  selenium  \
  Pillow
